config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'pages/tweet', to: 'pages#tweet'
  post 'pages/connect_twitter', to: 'pages#connect_twitter'
  get '/auth/twitter/callback', to: 'pages#return_twitter'










end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
require 'RMagick'
include Magick

class PagesController < ApplicationController

  # Home page
  def home
  end

  # The text is written to the image
  def tweet
    img = ImageList.new("#{Rails.root}/public/base_img.jpg")
    txt = Draw.new
    c = 0

    # 50 characters in one row
    (params[:message].length/50 + 1).times do |i|
      img.annotate(txt, 0, 0, 0, 400 - c, params[:message][(0 + 50 * i)..50*(i+1)]) {
        txt.gravity = Magick::SouthGravity
        txt.pointsize = 20
        txt.stroke = '#de9007'
        txt.fill = '#de9007'
        # txt.font_weight = Magick::BoldWeight
        c += 50
      }
    end

    img.annotate(txt, 0, 0, 0, 400 - c, '#SmileMoreForAGoodDay') {
      txt.gravity = Magick::SouthGravity
      txt.pointsize = 20
      txt.stroke = '#cf0a2c'
      txt.fill = '#cf0a2c'
      # txt.font_weight = Magick::BoldWeight
      c += 50
    }

    # Giving file name and writing to file
    img.format = 'jpeg'
    fname = SecureRandom.hex(20)
    path = "#{Rails.root}/public/#{fname}.jpg"
    img.write(path)
    render json: { status: 200, path: path }
  end

  # Omniauth to twitter with path of file passed along
  def connect_twitter
    redirect_to "/auth/twitter?path=#{params['path']}"
  end

  # Return from omniauth along with path of file
  def return_twitter
    token = request.env['omniauth.auth'].credentials['token']
    secret = request.env['omniauth.auth'].credentials['secret']
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET']
      config.access_token        = token
      config.access_token_secret = secret
    end

    # Posting to twitter
    client.update_with_media('#SmileMoreForAGoodDay', File.new(params[:path]))
    flash[:success] = 'Tweet Successful!! #SmileMoreForAGoodDay'

    # Deleting file
    File.delete(params['path']) if File.exist?(params['path'])
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default chalkboard mob-navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("logo.svg", alt: 'logo', class: "logo") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse show-menu" id="menu">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#section2">Meet The Project</a></li>
        <li><a href="#section3">Share A Smile</a></li>
        <li><a href="#">Making of</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodday</title>
    <meta charset="utf-8">
    <meta name="theme-color" content="#b66934">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".navbar" data-offset="200">

    <%= render 'layouts/navbar' %>

    <%= yield %>

  </body>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/pages/home.html.erb

<div class="section1" id="section1">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div><!--col-md-* end-->
    </div><!--row end-->
    <div class="text-center">
      <%= image_tag("goodday.png", alt: 'biscuit', class: "biscuit-img img-responsive") %>
      <br>
      <div class="chalkboard hd1">#SmileMoreForAGoodDay</div>
      <br><br><br>
      <div class="scroll-txt">
        Scroll down<br>
        to know more!
      </div>
      <%= image_tag("scroll.png", alt: 'scroll', class: "scroll") %>
    </div>
  </div><!--container end-->
</div><!--section1 end-->


<div class="section2" id="section2">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 col-xs-6">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 col-xs-6">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-8">
        <div class="text-center">
        <div class="sec2-mgtop"></div>
          <div class="chalkboard hd2">Flip the Good Day Cookie</div>
          <div class="sec2-txt">See the Beautiful Magic Behind the Cookie</div>
        </div><!--text-center-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 col-xs-6">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 col-xs-6">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
      <div class="col-sm-2 hidden-xs">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag("cookie1.png", alt: 'cookie1', class: "img-responsive") %>
            </div>
            <div class="back">
              <%= image_tag("cookie2.png", alt: 'cookie2', class: "img-responsive") %>
            </div>
          </div><!--flipper-->
        </div><!--flip-container-->
      </div><!--col-sm-* end-->
    </div><!--row end-->
  </div><!--container end-->
</div><!--section1 end-->



<div class="section3" id="section3">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6 text-center">
        <div class="chalkboard hd2 error-tw">Share A Smile</div>
        <div class="sec2-txt">Tweet a message and share a smile</div>
        <br><br>
        <div class="tweet-bar">
          <label class="control-label sr-only" for="inputGroupSuccess4">Input group with success</label>
          <div class="input-group">
            <input type="text" class="form-control tweet-bar-txt" placeholder="Tweet your Heart Out !" id="tweet-message">
            <span class="input-group-addon">
              <button class="tweet-btn" id="tweet-submit">
                <%= image_tag("tw.png", alt: 'tweet', class: "tweet") %>
              </button>
            </span>
          </div><!--input-group end-->
        </div><!--tweet bar end-->
        <%= form_tag pages_connect_twitter_path, id: 'path_form' do %>
          <%= hidden_field_tag 'path', nil, id: 'file_path' %>
          <%= submit_tag 'save', class: 'collapse', id: 'submit_path' %>
        <% end %>
      </div><!--col-sm-* end-->
    </div><!--row end-->
    <br>
    <div class="load_div hide">
      <div id="loader"></div>
    </div>
    <br>
  </div><!--container end-->
</div><!--section1 end-->

